services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/AnroxRamos/Esp32Mongo.git
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false  # Se configurará manualmente en el dashboard de Render
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
version: "1"
