services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/AnroxRamos/Esp32Mongo
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Test:12345@cluster0.7zhck.mongodb.net/BasePryEsp32?retryWrites=true&w=majority
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
